/**
 * Site search — a custom interface over the Pagefind JavaScript API.
 *
 * Pagefind indexes the generated site after the Eleventy build and writes a
 * static, chunked index into /pagefind/. Querying it is a handful of range
 * requests for the chunks a query actually touches, so there is no search
 * server and nothing leaves the browser.
 *
 * The page works without this file: the noscript block explains the
 * requirement and points at /all/, which lists the same content.
 */

const form = document.querySelector(".search-form");
const input = document.querySelector("#q");
const status = document.querySelector("#search-status");
const results = document.querySelector("#search-results");

const DEBOUNCE_MS = 200;
const MAX_RESULTS = 20;

/* Static markup, written here rather than assembled from search output. */
const resultTemplate = document.createElement("template");
resultTemplate.innerHTML = `
  <li>
    <h3><a></a></h3>
    <p class="search-excerpt"></p>
  </li>`;

/**
 * Pagefind escapes these five characters in excerpts. Decoding them by hand
 * keeps the whole render path free of innerHTML.
 */
const ENTITIES = {
  "&amp;": "&",
  "&lt;": "<",
  "&gt;": ">",
  "&quot;": '"',
  "&#39;": "'",
  "&apos;": "'",
};

function decodeEntities(text) {
  return text.replace(/&(?:amp|lt|gt|quot|#39|apos);/g, (match) => ENTITIES[match]);
}

/**
 * Rebuilds an excerpt as text nodes and real <mark> elements instead of
 * assigning Pagefind's HTML string to innerHTML.
 */
function renderExcerpt(container, excerpt) {
  container.replaceChildren();
  for (const part of excerpt.split(/(<mark>[\s\S]*?<\/mark>)/g)) {
    if (!part) continue;
    const highlighted = part.match(/^<mark>([\s\S]*?)<\/mark>$/);
    if (highlighted) {
      const mark = document.createElement("mark");
      mark.textContent = decodeEntities(highlighted[1]);
      container.append(mark);
    } else {
      container.append(document.createTextNode(decodeEntities(part)));
    }
  }
}

let pagefindPromise = null;

function loadPagefind() {
  if (!pagefindPromise) {
    pagefindPromise = import("/pagefind/pagefind.js").then(async (module) => {
      await module.options({ excerptLength: 25 });
      await module.init();
      return module;
    });
  }
  return pagefindPromise;
}

async function runSearch(query) {
  const trimmed = query.trim();

  if (trimmed === "") {
    results.replaceChildren();
    status.textContent = "Type a query to search.";
    return;
  }

  status.textContent = `Searching for “${trimmed}”…`;

  let pagefind;
  try {
    pagefind = await loadPagefind();
  } catch {
    results.replaceChildren();
    status.textContent =
      "The search index isn’t available. It is generated by the production build — run npm run build, or browse the full page listing instead.";
    return;
  }

  let hits;
  try {
    const search = await pagefind.search(trimmed);
    hits = await Promise.all(search.results.slice(0, MAX_RESULTS).map((hit) => hit.data()));
  } catch {
    results.replaceChildren();
    status.textContent = "Something went wrong running that search. Try again.";
    return;
  }

  // A slower earlier query must not overwrite a newer one.
  if (input.value.trim() !== trimmed) return;

  results.replaceChildren();

  if (hits.length === 0) {
    status.textContent = `No results for “${trimmed}”.`;
    return;
  }

  const fragment = document.createDocumentFragment();
  for (const hit of hits) {
    const node = resultTemplate.content.cloneNode(true);
    const link = node.querySelector("a");
    link.textContent = hit.meta?.title || hit.url;
    link.setAttribute("href", hit.url);
    renderExcerpt(node.querySelector(".search-excerpt"), hit.excerpt ?? "");
    fragment.append(node);
  }
  results.append(fragment);

  status.textContent = `${hits.length} ${hits.length === 1 ? "result" : "results"} for “${trimmed}”.`;
}

if (form && input && status && results) {
  let debounceId = null;

  input.addEventListener("input", () => {
    clearTimeout(debounceId);
    debounceId = setTimeout(() => runSearch(input.value), DEBOUNCE_MS);
  });

  form.addEventListener("submit", (event) => {
    // Everything happens in place; a page reload would only lose the results.
    event.preventDefault();
    clearTimeout(debounceId);
    const query = input.value.trim();
    const url = query ? `?q=${encodeURIComponent(query)}` : location.pathname;
    history.replaceState(null, "", url);
    runSearch(query);
  });

  // Make a search linkable: /search/?q=canvas runs on load.
  const initial = new URLSearchParams(location.search).get("q");
  if (initial) {
    input.value = initial;
    runSearch(initial);
  }
}
